### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by primetoxinz** [primetoxinz/something#1]
- [ ] 1 Hardcore Armor
- [ ] 2 Hardcore Baking
- [ ] 3 Hardcore Beacons
	* [ ] Hellfire 
- [ ] 4 Hardcore Bedding
- [ ] 5 Hardcore Bonemeal
- [ ] 6 Hardcore Bouncing
- [ ] 7 Hardcore Bucket
- [ ] 8 Hardcore Buoy [Optional] [Default]
- [ ] 9 Hardcore Chests
- [ ] 10 Hardcore Chicken
- [ ] 11 Hardcore Darkness
- [ ] 12 Hardcore Explosives
- [ ] 13 Hardcore Fishing
- [ ] 14 Hardcore Grinding
- [ ] 15 Hardcore Hunger
- [ ] 16 Hardcore Info
- [ ] 17 Hardcore Lactation
- [ ] 18 Hardcore Melons
- [ ] 19 Hardcore Movement
- [ ] 20 Hardcore Ores
- [ ] 21 Hardcore Player Names [Optional]
- [ ] 22 Hardcore Sheep
- [ ] 23 Hardcore Sinkholes
- [ ] 24 Hardcore Spawn
- [ ] 25 Hardcore Stratification
- [ ] 26 Hardcore Tools and Weapons
- [ ] 27 Hardcore Villagers
- [ ] 28 Hardcore Wood
- [ ] 29 Hardcore Packing
